import numpy as np
import matplotlib.pyplot as plt

method=5;
method_name=['pjc','pgs','ljc','lgs','ads']

data = np.loadtxt("2d_data.txt")
cp = np.loadtxt("2d_cp.txt")
re = np.loadtxt("2d_residual.txt")
#rem = np.loadtxt("residual_map.txt")
#print(data)
x = np.array(data[0,:]).reshape((51,51))
y = np.array(data[1,:]).reshape((51,51))
#print(re[2,:])
#O = np.array(data[2,:]).reshape((51,51))
#F = np.array(data[4,:]).reshape((51,51))
#Rem = np.array(rem[1,:]).reshape((51,51))
#R = np.array(re[0,:])
#plt.figure()
#ax = fig.add_subplot(111, projection='3d')
#for i in range(51):
#    plt.plot(x[:,i],y[:,i],'-k',linewidth=0.5)
#    plt.plot(x[i,:],y[i,:],'-k',linewidth=0.5)
#levels= np.linspace(np.min(Rem),np.max(Rem),20)
#print(np.min(Rem))
#print(np.max(Rem))
#plt.plot(x[0,:],cp[3,:],linewidth=0.5)
#plt.contour(x,y,F, levels=levels)
#plt.contour(x,y,Rem, levels=levels);
#ax.plot_surface(x,y,Rem,edgecolor='royalblue', lw=0.5, rstride=8, cstride=8,
#                alpha=0.3)
#plt.xlim([-0.1,1.1])
#plt.ylim([-0.3,0.2])
#plt.colorbar()
#plt.title("Mesh near airfoil")
plt.figure(1)
plt.yscale("log")
plt.plot(re[0,:],'k',label="pjc")
plt.plot(re[1,:],'--k',label="pgs")
plt.plot(re[2,:],'-.k',label="ljc")
plt.plot(re[3,:],':k',label="lgs")
plt.plot(re[4,:],'0.5',label="adi")
plt.title("residual for all methods")
plt.xlabel("step")
plt.ylabel("residual")
plt.legend()
plt.savefig("residual_all.png")

plt.figure(2)
plt.plot(x[0,:],cp[0,:],'k',label="pjc")
plt.plot(x[0,:],cp[1,:],'--k',label="pgs")
plt.plot(x[0,:],cp[2,:],'0.8',label="ljc",linewidth=4)
plt.plot(x[0,:],cp[3,:],':k',label="lgs",linewidth=3)
plt.plot(x[0,:],cp[4,:],'0.5',':',label="adi",linewidth=2)
plt.xlim([-0.1,1.1])
plt.ylim([-0.2,0.25])
plt.title("$C_p$ for all methods")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.savefig("cp_all.png")

plt.figure(3)
for i in range(51):
    plt.plot(x[:,i],y[:,i],'-k',linewidth=0.5)
    plt.plot(x[i,:],y[i,:],'-k',linewidth=0.5)
plt.title("grid")
plt.xlabel("x")
plt.ylabel("y")
plt.xlim([-1,2])
plt.ylim([0,3])
plt.savefig("grid.png")
